"""
HTML Report Generator
Renders situation-based synthesis output as a readable HTML document.
"""

import re
from datetime import datetime
from pathlib import Path
from typing import Any

from ..config.settings import settings


def clean_citations_html(text: str) -> str:
    """Convert ^[N,M] citation markers to styled HTML spans."""
    if not text:
        return text
    return re.sub(
        r"\^\[([0-9,\s]+)\]",
        r'<span class="citation">[\1]</span>',
        text,
    )


def _epistemic_badge(status: str) -> str:
    """Render an epistemic status as a colored badge."""
    colors = {
        "reported_fact": "#2d6a4f",
        "single_source": "#e76f51",
        "consensus": "#264653",
        "consensus_view": "#264653",
        "speculation": "#9a031e",
    }
    color = colors.get(status, "#555")
    label = status.replace("_", " ")
    return f'<span class="badge" style="background:{color}">{label}</span>'


def generate_html_report(synthesis_data: dict[str, Any]) -> str:
    """Generate a complete HTML report from synthesis data."""
    situations = synthesis_data.get("situations", [])
    thin_coverage = synthesis_data.get("thin_coverage", [])
    metadata = synthesis_data.get("metadata", {})

    now = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    articles = metadata.get("articles_analyzed", 0)
    clusters_analyzed = metadata.get("clusters_analyzed", 0)
    clusters_thin = metadata.get("clusters_thin", 0)
    threshold = metadata.get("analysis_threshold", "2+ articles")

    situations_html = "\n".join(_render_situation(s, i) for i, s in enumerate(situations, 1))

    thin_html = ""
    if thin_coverage:
        items = "\n".join(_render_thin_item(t) for t in thin_coverage)
        thin_html = f"""
        <section class="thin-coverage">
            <h2>Thin Coverage</h2>
            <p class="meta">Topics with insufficient coverage for full analysis.</p>
            {items}
        </section>
        """

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>InsightWeaver Intelligence Brief - {now}</title>
<style>
{_get_css()}
</style>
</head>
<body>
<header>
    <h1>Intelligence Brief</h1>
    <p class="dateline">{now}</p>
    <p class="meta">
        {articles} articles | {clusters_analyzed} situations analyzed |
        {clusters_thin} thin coverage | Threshold: {threshold}
    </p>
</header>
<main>
    {situations_html}
    {thin_html}
</main>
<footer>
    <p>Generated by InsightWeaver. RSS is the only input source.
    Frame validation and feed curation are the user's responsibility.</p>
</footer>
</body>
</html>"""


def _render_situation(situation: dict, index: int) -> str:
    """Render a single situation as HTML."""
    title = clean_citations_html(situation.get("title", "Untitled"))
    narrative = situation.get("narrative", "")
    actors = situation.get("actors", [])
    power = situation.get("power_dynamics", {})
    frame = situation.get("coverage_frame", {})
    futures = situation.get("where_this_goes", {})
    causal = situation.get("causal_structure", {})
    gaps = situation.get("information_gaps", [])

    # Narrative paragraphs
    narrative_html = ""
    if narrative:
        paragraphs = clean_citations_html(narrative).split("\n\n")
        narrative_html = "\n".join(f"<p>{p.strip()}</p>" for p in paragraphs if p.strip())

    # Actors
    actors_html = ""
    if actors:
        actor_items = ""
        for a in actors:
            badge = _epistemic_badge(a.get("epistemic_status", ""))
            actor_items += f"""
            <div class="actor">
                <strong>{a.get("name", "Unknown")}</strong> {badge}
                <div class="actor-detail">Role: {a.get("role", "")}</div>
                <div class="actor-detail">Interests: {a.get("interests", "")}</div>
            </div>"""
        actors_html = f'<div class="section"><h3>Actors</h3>{actor_items}</div>'

    # Power dynamics
    power_html = ""
    if power:
        rows = ""
        for label, key in [
            ("Benefits", "who_benefits"),
            ("Harmed", "who_is_harmed"),
            ("Decides", "who_decides"),
        ]:
            val = power.get(key, "")
            if val:
                rows += (
                    f"<tr><td class='label'>{label}</td><td>{clean_citations_html(val)}</td></tr>"
                )
        if rows:
            power_html = f'<div class="section"><h3>Power Dynamics</h3><table>{rows}</table></div>'

    # Coverage frame / narrative layers
    frame_html = ""
    if frame:
        parts = []
        if frame.get("narrative_layers"):
            parts.append(f"<p><strong>Narrative layers:</strong> {frame['narrative_layers']}</p>")
        elif frame.get("dominant_frame"):
            parts.append(f"<p><strong>Frame:</strong> {frame['dominant_frame']}</p>")
        if frame.get("fractures"):
            parts.append(f"<p><strong>Fractures:</strong> {frame['fractures']}</p>")
        if frame.get("bridges"):
            parts.append(f"<p><strong>Bridges:</strong> {frame['bridges']}</p>")
        if frame.get("structural_absences"):
            parts.append(
                f'<p><strong>Hard to see:</strong> <span class="absence">{frame["structural_absences"]}</span></p>'
            )
        if parts:
            frame_html = f'<div class="section frame-section"><h3>What the Coverage Makes Visible and Invisible</h3>{"".join(parts)}</div>'

    # Where this goes
    futures_html = ""
    if futures:
        parts = []
        if futures.get("branching_paths"):
            parts.append(
                f"<p><strong>Paths:</strong> {clean_citations_html(futures['branching_paths'])}</p>"
            )
        if futures.get("unresolved_question"):
            parts.append(
                f'<p class="key-question"><strong>Key question:</strong> {futures["unresolved_question"]}</p>'
            )
        if futures.get("what_to_watch"):
            parts.append(f"<p><strong>Watch for:</strong> {futures['what_to_watch']}</p>")
        if parts:
            futures_html = f'<div class="section futures-section"><h3>Where This Goes</h3>{"".join(parts)}</div>'

    # Causal structure (backward compat)
    causal_html = ""
    if causal:
        parts = []
        for label, key in [
            ("Forces", "forces"),
            ("Constraints", "constraints"),
            ("Dependencies", "dependencies"),
        ]:
            val = causal.get(key, "")
            if val:
                parts.append(f"<p><strong>{label}:</strong> {clean_citations_html(val)}</p>")
        if parts:
            causal_html = f'<div class="section"><h3>Causal Structure</h3>{"".join(parts)}</div>'

    # Information gaps
    gaps_html = ""
    if gaps:
        gap_items = ""
        for g in gaps:
            missing = g.get("what_is_missing", "")
            why = g.get("why_it_matters", "")
            why_missing = g.get("why_missing", "")
            feed = g.get("feed_recommendation", "")
            gap_items += f"""
            <div class="gap">
                <div class="gap-title">{missing}</div>
                {f'<div class="gap-detail">Why it matters: {why}</div>' if why else ""}
                {f'<div class="gap-detail">Why missing: {why_missing}</div>' if why_missing else ""}
                {f'<div class="gap-detail">Suggested source: <em>{feed}</em></div>' if feed else ""}
            </div>"""
        gaps_html = f'<div class="section gaps-section"><h3>Information Gaps</h3>{gap_items}</div>'

    return f"""
    <article class="situation">
        <h2><span class="situation-number">{index}</span> {title}</h2>
        <div class="narrative">{narrative_html}</div>
        {actors_html}
        {power_html}
        {frame_html}
        {futures_html}
        {causal_html}
        {gaps_html}
    </article>"""


def _render_thin_item(item: dict) -> str:
    """Render a thin coverage item."""
    title = item.get("title", "Unknown")
    count = item.get("article_count", 0)
    sources = ", ".join(item.get("sources", []))
    note = item.get("note", "")
    return f"""
    <div class="thin-item">
        <strong>{title}</strong>
        <span class="meta">{count} article(s) | {sources}</span>
        {f'<p class="thin-note">{note}</p>' if note else ""}
    </div>"""


def save_html_report(synthesis_data: dict[str, Any]) -> Path:
    """Generate and save HTML report. Returns the file path."""
    html = generate_html_report(synthesis_data)

    reports_dir = settings.briefings_dir
    reports_dir.mkdir(parents=True, exist_ok=True)

    date_str = datetime.now().strftime("%Y-%m-%d_%H%M")
    filename = f"brief_{date_str}.html"
    filepath = reports_dir / filename

    filepath.write_text(html, encoding="utf-8")
    return filepath


def _get_css() -> str:
    """Return the stylesheet for the HTML report."""
    return """
    * { margin: 0; padding: 0; box-sizing: border-box; }

    body {
        font-family: 'Georgia', 'Times New Roman', serif;
        line-height: 1.7;
        color: #1a1a1a;
        background: #fafaf7;
        max-width: 52rem;
        margin: 0 auto;
        padding: 2rem 1.5rem;
    }

    header {
        border-bottom: 3px solid #1a1a1a;
        padding-bottom: 1.5rem;
        margin-bottom: 2.5rem;
    }

    header h1 {
        font-size: 2rem;
        font-weight: 700;
        letter-spacing: -0.02em;
        margin-bottom: 0.25rem;
    }

    .dateline {
        font-style: italic;
        color: #555;
        margin-bottom: 0.5rem;
    }

    .meta {
        font-family: 'Helvetica Neue', Arial, sans-serif;
        font-size: 0.85rem;
        color: #777;
    }

    article.situation {
        margin-bottom: 3rem;
        padding-bottom: 2rem;
        border-bottom: 1px solid #ddd;
    }

    article.situation h2 {
        font-size: 1.35rem;
        font-weight: 700;
        line-height: 1.3;
        margin-bottom: 1rem;
        color: #1a1a1a;
    }

    .situation-number {
        display: inline-block;
        background: #1a1a1a;
        color: #fafaf7;
        width: 1.8rem;
        height: 1.8rem;
        line-height: 1.8rem;
        text-align: center;
        border-radius: 50%;
        font-size: 0.9rem;
        margin-right: 0.5rem;
        vertical-align: middle;
    }

    .narrative p {
        margin-bottom: 1rem;
        text-align: justify;
    }

    .section {
        margin: 1.5rem 0;
        padding: 1rem 1.25rem;
        background: #f5f5f0;
        border-left: 3px solid #ccc;
        border-radius: 0 4px 4px 0;
    }

    .section h3 {
        font-family: 'Helvetica Neue', Arial, sans-serif;
        font-size: 0.85rem;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 0.08em;
        color: #555;
        margin-bottom: 0.75rem;
    }

    .frame-section { border-left-color: #e76f51; }
    .futures-section { border-left-color: #264653; }
    .gaps-section { border-left-color: #9a031e; }

    .section p { margin-bottom: 0.5rem; font-size: 0.95rem; }

    .key-question {
        background: #fff;
        padding: 0.75rem 1rem;
        border-radius: 4px;
        border: 1px solid #264653;
        margin: 0.5rem 0;
    }

    .absence { color: #9a031e; }

    .badge {
        display: inline-block;
        font-family: 'Helvetica Neue', Arial, sans-serif;
        font-size: 0.7rem;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        color: #fff;
        padding: 0.15rem 0.5rem;
        border-radius: 3px;
        vertical-align: middle;
        margin-left: 0.3rem;
    }

    .citation {
        font-family: 'Helvetica Neue', Arial, sans-serif;
        font-size: 0.75rem;
        color: #2d6a4f;
        font-weight: 600;
    }

    .actor {
        margin-bottom: 0.75rem;
        padding-bottom: 0.5rem;
        border-bottom: 1px solid #e0e0d8;
    }

    .actor:last-child { border-bottom: none; }

    .actor-detail {
        font-size: 0.9rem;
        color: #444;
        margin-left: 0.5rem;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    table td {
        padding: 0.4rem 0.5rem;
        vertical-align: top;
        font-size: 0.95rem;
    }

    td.label {
        font-weight: 700;
        width: 5rem;
        color: #555;
        font-family: 'Helvetica Neue', Arial, sans-serif;
        font-size: 0.85rem;
        text-transform: uppercase;
    }

    .gap {
        margin-bottom: 1rem;
        padding: 0.75rem 1rem;
        background: #fff;
        border-radius: 4px;
        border: 1px solid #e0d8d0;
    }

    .gap-title {
        font-weight: 700;
        color: #9a031e;
        margin-bottom: 0.25rem;
    }

    .gap-detail {
        font-size: 0.9rem;
        color: #555;
        margin-top: 0.2rem;
    }

    .thin-coverage {
        margin-top: 2rem;
        padding-top: 1.5rem;
        border-top: 1px solid #ddd;
    }

    .thin-coverage h2 {
        font-size: 1.1rem;
        margin-bottom: 0.5rem;
    }

    .thin-item {
        padding: 0.5rem 0;
        border-bottom: 1px solid #eee;
    }

    .thin-item strong { font-size: 0.95rem; }
    .thin-item .meta { display: block; margin-top: 0.15rem; }
    .thin-note { font-size: 0.9rem; color: #555; margin-top: 0.25rem; }

    footer {
        margin-top: 3rem;
        padding-top: 1rem;
        border-top: 1px solid #ddd;
        font-size: 0.8rem;
        color: #999;
        text-align: center;
    }

    @media (max-width: 600px) {
        body { padding: 1rem; }
        header h1 { font-size: 1.5rem; }
        article.situation h2 { font-size: 1.15rem; }
    }
    """
